# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI_ahsanayaz.com

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm install
    - name: Build Web
      run: npm run clean && npm run build
    - name: Deploy
      steps:
        - name: Deploy webhook request
          run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e6e65d1a4ac10c91f9660fb
